const nowPlayingMovies = [
  {
    adult: false,
    backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    genre_ids: [14, 12, 28],
    id: 763215,
    original_language: "en",
    original_title: "Damsel",
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 3001.85,
    poster_path: "/sMp34cNKjIb18UBOCoAv4DpCxwY.jpg",
    release_date: "2024-03-08",
    title: "Damsel",
    video: false,
    vote_average: 7.266,
    vote_count: 858,
  },
  {
    adult: false,
    backdrop_path: "/gJL5kp5FMopB2sN4WZYnNT5uO0u.jpg",
    genre_ids: [28, 12, 16, 35, 10751],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 3781.812,
    poster_path: "/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 6.911,
    vote_count: 157,
  },
  {
    adult: false,
    backdrop_path: "/xvk5AhfhgQcTuaCQyq3XqAnhEma.jpg",
    genre_ids: [28, 12, 35],
    id: 848538,
    original_language: "en",
    original_title: "Argylle",
    overview:
      "When the plots of reclusive author Elly Conway's fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway's fictional world and her real one begins to blur.",
    popularity: 1674.191,
    poster_path: "/95VlSEfLMqeX36UVcHJuNlWEpwf.jpg",
    release_date: "2024-01-31",
    title: "Argylle",
    video: false,
    vote_average: 6.142,
    vote_count: 604,
  },
  {
    adult: false,
    backdrop_path: "/mDeUmPe4MF35WWlAqj4QFX5UauJ.jpg",
    genre_ids: [28, 27, 53],
    id: 1096197,
    original_language: "pt",
    original_title: "No Way Up",
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 1709.062,
    poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    release_date: "2024-01-18",
    title: "No Way Up",
    video: false,
    vote_average: 6.073,
    vote_count: 239,
  },
  {
    adult: false,
    backdrop_path: "/cu5Qk2QHxOyyMrD3Bq93DxgmJer.jpg",
    genre_ids: [28, 80],
    id: 1046090,
    original_language: "zh",
    original_title: "周處除三害",
    overview:
      "The arrogant, third most-wanted criminal in Taiwan, decides to get rid of the top two competitors and crowns himself the most-wanted criminal before dying.",
    popularity: 1407.442,
    poster_path: "/7IJ7F8tX7IAkpUdaGovOBJqORnJ.jpg",
    release_date: "2023-10-06",
    title: "The Pig, the Snake and the Pigeon",
    video: false,
    vote_average: 7.557,
    vote_count: 87,
  },
  {
    adult: false,
    backdrop_path: "/47olX0FCvUCfAqlp8cK0O5fKLav.jpg",
    genre_ids: [16, 35, 878],
    id: 1239251,
    original_language: "en",
    original_title: "Megamind vs. the Doom Syndicate",
    overview:
      "Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
    popularity: 1275.225,
    poster_path: "/yRZfiG1QpRkBc7fAmxfcR7Md5EC.jpg",
    release_date: "2024-03-01",
    title: "Megamind vs. the Doom Syndicate",
    video: false,
    vote_average: 5.736,
    vote_count: 121,
  },
  {
    adult: false,
    backdrop_path: "/o6e8Y0Q7RZIWi4qcJq4s5OYOVJs.jpg",
    genre_ids: [878, 10749, 35],
    id: 792307,
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    popularity: 1077.325,
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    release_date: "2023-12-07",
    title: "Poor Things",
    video: false,
    vote_average: 7.868,
    vote_count: 2390,
  },
  {
    adult: false,
    backdrop_path: "/8uVKfOJUhmybNsVh089EqLHUYEG.jpg",
    genre_ids: [878, 12],
    id: 693134,
    original_language: "en",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    popularity: 1180.358,
    poster_path: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    release_date: "2024-02-27",
    title: "Dune: Part Two",
    video: false,
    vote_average: 8.406,
    vote_count: 1786,
  },
  {
    adult: false,
    backdrop_path: "/ekRp1sEA8pnuzVHQkUESTgNSKdW.jpg",
    genre_ids: [878, 28, 80],
    id: 932420,
    original_language: "en",
    original_title: "Code 8 Part II",
    overview:
      "In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.",
    popularity: 1146.099,
    poster_path: "/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg",
    release_date: "2024-02-27",
    title: "Code 8 Part II",
    video: false,
    vote_average: 6.608,
    vote_count: 297,
  },
  {
    adult: false,
    backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: "en",
    original_title: "Land of Bad",
    overview:
      "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
    popularity: 1067.477,
    poster_path: "/lYwjlcBjokC9EhfzfAOkTMQd5Ku.jpg",
    release_date: "2024-01-25",
    title: "Land of Bad",
    video: false,
    vote_average: 6.994,
    vote_count: 348,
  },
  {
    adult: false,
    backdrop_path: "/gklkxY0veMajdCiGe6ggsh07VG2.jpg",
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    popularity: 903.985,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.565,
    vote_count: 945,
  },
  {
    adult: false,
    backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 806.344,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.113,
    vote_count: 7217,
  },
  {
    adult: false,
    backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
    genre_ids: [35, 10749],
    id: 1072790,
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    popularity: 836.569,
    poster_path: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
    release_date: "2023-12-21",
    title: "Anyone But You",
    video: false,
    vote_average: 7.048,
    vote_count: 1016,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 663.721,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    video: false,
    vote_average: 7.788,
    vote_count: 10804,
  },
  {
    adult: false,
    backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
    genre_ids: [28, 14],
    id: 634492,
    original_language: "en",
    original_title: "Madame Web",
    overview:
      "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
    popularity: 595.689,
    poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    release_date: "2024-02-14",
    title: "Madame Web",
    video: false,
    vote_average: 5.356,
    vote_count: 477,
  },
  {
    adult: false,
    backdrop_path: "/6SLyu9ygASsrOqkCpjAwtyG9PWW.jpg",
    genre_ids: [10751, 878, 28, 35],
    id: 1094556,
    original_language: "en",
    original_title: "The Thundermans Return",
    overview:
      "Twins Phoebe and Max are enjoying their superhero lifestyle, but when one 'save' goes awry, the Thundermans are sent back to Hiddenville. While Hank and Barb enjoy their return, and Billy and Nora look forward to a normal high school life, Max and Phoebe are determined to regain their superhero status.",
    popularity: 583.77,
    poster_path: "/rz98XwP0VJq6e1jnWDCxn6EDLfP.jpg",
    release_date: "2024-03-07",
    title: "The Thundermans Return",
    video: false,
    vote_average: 7.767,
    vote_count: 43,
  },
  {
    adult: false,
    backdrop_path: "/xi2pblvQtCnh26SeOYzx1YX3DLT.jpg",
    genre_ids: [80, 28, 53],
    id: 1227816,
    original_language: "en",
    original_title: "Red Right Hand",
    overview:
      "Cash is trying to live a quiet, honest life in a small Appalachian town. When a vicious crime boss forces him back into her services, he soon learns he's capable of anything -- even killing -- to protect his family and his home.",
    popularity: 550.354,
    poster_path: "/vfEG79SQIg3p6B8rBLVeIo2BBhb.jpg",
    release_date: "2024-02-22",
    title: "Red Right Hand",
    video: false,
    vote_average: 7,
    vote_count: 54,
  },
  {
    adult: false,
    backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
    genre_ids: [16, 10751, 14, 12],
    id: 1022796,
    original_language: "en",
    original_title: "Wish",
    overview:
      "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
    popularity: 499.767,
    poster_path: "/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
    release_date: "2023-11-13",
    title: "Wish",
    video: false,
    vote_average: 6.624,
    vote_count: 874,
  },
  {
    adult: false,
    backdrop_path: "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
    genre_ids: [16, 12, 14],
    id: 508883,
    original_language: "ja",
    original_title: "君たちはどう生きるか",
    overview:
      "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
    popularity: 455.787,
    poster_path: "/f4oZTcfGrVTXKTWg157AwikXqmP.jpg",
    release_date: "2023-07-14",
    title: "The Boy and the Heron",
    video: false,
    vote_average: 7.4,
    vote_count: 1100,
  },
  {
    adult: false,
    backdrop_path: "/824e60sDlEXUP1vXCYNqh5RSlI5.jpg",
    genre_ids: [878, 12, 18],
    id: 636706,
    original_language: "en",
    original_title: "Spaceman",
    overview:
      "During a research mission, an astronaut discovers that his marriage is in trouble. Luckily, he has the help of a mysterious creature hidden in his ship.",
    popularity: 464.305,
    poster_path: "/f46WvKEsBn98WJbPJcO47ZoKn6B.jpg",
    release_date: "2024-02-23",
    title: "Spaceman",
    video: false,
    vote_average: 6.707,
    vote_count: 382,
  },
];

const popularMovies = [
  {
    adult: false,
    backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    genre_ids: [14, 12, 28],
    id: 763215,
    original_language: "en",
    original_title: "Damsel",
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 3001.85,
    poster_path: "/sMp34cNKjIb18UBOCoAv4DpCxwY.jpg",
    release_date: "2024-03-08",
    title: "Damsel",
    video: false,
    vote_average: 7.3,
    vote_count: 841,
  },
  {
    adult: false,
    backdrop_path: "/gJL5kp5FMopB2sN4WZYnNT5uO0u.jpg",
    genre_ids: [28, 12, 16, 35, 10751],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 3781.812,
    poster_path: "/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 6.9,
    vote_count: 156,
  },
  {
    adult: false,
    backdrop_path: "/xvk5AhfhgQcTuaCQyq3XqAnhEma.jpg",
    genre_ids: [28, 12, 35],
    id: 848538,
    original_language: "en",
    original_title: "Argylle",
    overview:
      "When the plots of reclusive author Elly Conway's fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway's fictional world and her real one begins to blur.",
    popularity: 1674.191,
    poster_path: "/95VlSEfLMqeX36UVcHJuNlWEpwf.jpg",
    release_date: "2024-01-31",
    title: "Argylle",
    video: false,
    vote_average: 6.134,
    vote_count: 599,
  },
  {
    adult: false,
    backdrop_path: "/mDeUmPe4MF35WWlAqj4QFX5UauJ.jpg",
    genre_ids: [28, 27, 53],
    id: 1096197,
    original_language: "pt",
    original_title: "No Way Up",
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 1709.062,
    poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    release_date: "2024-01-18",
    title: "No Way Up",
    video: false,
    vote_average: 6.049,
    vote_count: 237,
  },
  {
    adult: false,
    backdrop_path: "/cu5Qk2QHxOyyMrD3Bq93DxgmJer.jpg",
    genre_ids: [28, 80],
    id: 1046090,
    original_language: "zh",
    original_title: "周處除三害",
    overview:
      "The arrogant, third most-wanted criminal in Taiwan, decides to get rid of the top two competitors and crowns himself the most-wanted criminal before dying.",
    popularity: 1407.442,
    poster_path: "/7IJ7F8tX7IAkpUdaGovOBJqORnJ.jpg",
    release_date: "2023-10-06",
    title: "The Pig, the Snake and the Pigeon",
    video: false,
    vote_average: 7.557,
    vote_count: 87,
  },
  {
    adult: false,
    backdrop_path: "/oFAukXiMPrwLpbulGmB5suEZlrm.jpg",
    genre_ids: [28, 12, 878, 14, 18],
    id: 624091,
    original_language: "id",
    original_title: "Sri Asih",
    overview:
      "Alana discover the truth about her origin: she’s not an ordinary human being. She may be the gift for humanity and become its protector as Sri Asih. Or a destruction, if she can’t control her anger.",
    popularity: 1704.084,
    poster_path: "/wShcJSKMFg1Dy1yq7kEZuay6pLS.jpg",
    release_date: "2022-11-17",
    title: "Sri Asih",
    video: false,
    vote_average: 6.3,
    vote_count: 26,
  },
  {
    adult: false,
    backdrop_path: "/47olX0FCvUCfAqlp8cK0O5fKLav.jpg",
    genre_ids: [16, 35, 878],
    id: 1239251,
    original_language: "en",
    original_title: "Megamind vs. the Doom Syndicate",
    overview:
      "Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
    popularity: 1275.225,
    poster_path: "/yRZfiG1QpRkBc7fAmxfcR7Md5EC.jpg",
    release_date: "2024-03-01",
    title: "Megamind vs. the Doom Syndicate",
    video: false,
    vote_average: 5.736,
    vote_count: 121,
  },
  {
    adult: false,
    backdrop_path: "/o6e8Y0Q7RZIWi4qcJq4s5OYOVJs.jpg",
    genre_ids: [878, 10749, 35],
    id: 792307,
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    popularity: 1077.325,
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    release_date: "2023-12-07",
    title: "Poor Things",
    video: false,
    vote_average: 7.87,
    vote_count: 2384,
  },
  {
    adult: false,
    backdrop_path: "/8uVKfOJUhmybNsVh089EqLHUYEG.jpg",
    genre_ids: [878, 12],
    id: 693134,
    original_language: "en",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    popularity: 1180.358,
    poster_path: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    release_date: "2024-02-27",
    title: "Dune: Part Two",
    video: false,
    vote_average: 8.4,
    vote_count: 1779,
  },
  {
    adult: false,
    backdrop_path: "/ekRp1sEA8pnuzVHQkUESTgNSKdW.jpg",
    genre_ids: [878, 28, 80],
    id: 932420,
    original_language: "en",
    original_title: "Code 8 Part II",
    overview:
      "In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.",
    popularity: 1146.099,
    poster_path: "/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg",
    release_date: "2024-02-27",
    title: "Code 8 Part II",
    video: false,
    vote_average: 6.608,
    vote_count: 295,
  },
  {
    adult: false,
    backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: "en",
    original_title: "Land of Bad",
    overview:
      "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
    popularity: 1067.477,
    poster_path: "/lYwjlcBjokC9EhfzfAOkTMQd5Ku.jpg",
    release_date: "2024-01-25",
    title: "Land of Bad",
    video: false,
    vote_average: 6.986,
    vote_count: 347,
  },
  {
    adult: false,
    backdrop_path: "/gklkxY0veMajdCiGe6ggsh07VG2.jpg",
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    popularity: 903.985,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.565,
    vote_count: 945,
  },
  {
    adult: false,
    backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
    genre_ids: [35, 10751, 14],
    id: 787699,
    original_language: "en",
    original_title: "Wonka",
    overview:
      "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
    popularity: 802.821,
    poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    release_date: "2023-12-06",
    title: "Wonka",
    video: false,
    vote_average: 7.2,
    vote_count: 2554,
  },
  {
    adult: false,
    backdrop_path: "/4Ep2KivIBUZbkS7kHjW7Qywnhhj.jpg",
    genre_ids: [28],
    id: 1049948,
    original_language: "en",
    original_title: "Vikings: Battle of Heirs",
    overview:
      "A young Viking must come to terms with the realization that he may be the King's son, who was switched at birth, but not before others try to take his rightful place.",
    popularity: 1050.14,
    poster_path: "/87goLbbqrJqAxqDS5cBsik1zKT.jpg",
    release_date: "2023-04-28",
    title: "Vikings: Battle of Heirs",
    video: false,
    vote_average: 7,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 806.344,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.115,
    vote_count: 7212,
  },
  {
    adult: false,
    backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
    genre_ids: [35, 10749],
    id: 1072790,
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    popularity: 836.569,
    poster_path: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
    release_date: "2023-12-21",
    title: "Anyone But You",
    video: false,
    vote_average: 7.033,
    vote_count: 1010,
  },
  {
    adult: false,
    backdrop_path: "/wqmemsQb8xcLVQkwt8WTYnMIYms.jpg",
    genre_ids: [28, 35],
    id: 1217409,
    original_language: "es",
    original_title: "Jaque Mate",
    overview:
      "Duque, an international secret agent who retired years ago after a traumatic event, is forced to return to action when a commando operative kidnaps his niece and forces him to steal a precious scientific formula as part of the ransom.",
    popularity: 679.967,
    poster_path: "/26VzK0GVAsZhVXIbv3qDKiwBYud.jpg",
    release_date: "2024-01-25",
    title: "Jaque Mate",
    video: false,
    vote_average: 4.6,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 663.721,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    video: false,
    vote_average: 7.788,
    vote_count: 10803,
  },
  {
    adult: false,
    backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
    genre_ids: [28, 14],
    id: 634492,
    original_language: "en",
    original_title: "Madame Web",
    overview:
      "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
    popularity: 595.689,
    poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    release_date: "2024-02-14",
    title: "Madame Web",
    video: false,
    vote_average: 5.361,
    vote_count: 471,
  },
  {
    adult: false,
    backdrop_path: "/6SLyu9ygASsrOqkCpjAwtyG9PWW.jpg",
    genre_ids: [10751, 878, 28, 35],
    id: 1094556,
    original_language: "en",
    original_title: "The Thundermans Return",
    overview:
      "Twins Phoebe and Max are enjoying their superhero lifestyle, but when one 'save' goes awry, the Thundermans are sent back to Hiddenville. While Hank and Barb enjoy their return, and Billy and Nora look forward to a normal high school life, Max and Phoebe are determined to regain their superhero status.",
    popularity: 583.77,
    poster_path: "/rz98XwP0VJq6e1jnWDCxn6EDLfP.jpg",
    release_date: "2024-03-07",
    title: "The Thundermans Return",
    video: false,
    vote_average: 7.767,
    vote_count: 43,
  },
];

const topRatedMovies = [
  {
    adult: false,
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 119.526,
    poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.704,
    vote_count: 25793,
  },
  {
    adult: false,
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 124.946,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.695,
    vote_count: 19590,
  },
  {
    adult: false,
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_language: "en",
    original_title: "The Godfather Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 82.765,
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather Part II",
    video: false,
    vote_average: 8.576,
    vote_count: 11836,
  },
  {
    adult: false,
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 76.704,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.566,
    vote_count: 15223,
  },
  {
    adult: false,
    backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    genre_ids: [18],
    id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 59.839,
    poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    video: false,
    vote_average: 8.54,
    vote_count: 8119,
  },
  {
    adult: false,
    backdrop_path: "/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg",
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 177.422,
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.54,
    vote_count: 15685,
  },
  {
    adult: false,
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 37.044,
    poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.533,
    vote_count: 4357,
  },
  {
    adult: false,
    backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 109.323,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.514,
    vote_count: 31625,
  },
  {
    adult: false,
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: "ko",
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    popularity: 131.297,
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    title: "Parasite",
    video: false,
    vote_average: 8.511,
    vote_count: 17284,
  },
  {
    adult: false,
    backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
    genre_ids: [14, 18, 80],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    popularity: 94.703,
    poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.508,
    vote_count: 16611,
  },
  {
    adult: false,
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    genre_ids: [16, 10749, 18],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 86.335,
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.497,
    vote_count: 10833,
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 107.161,
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.489,
    vote_count: 26791,
  },
  {
    adult: false,
    backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    genre_ids: [12, 14, 28],
    id: 122,
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    overview:
      "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
    popularity: 120.532,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-01",
    title: "The Lord of the Rings: The Return of the King",
    video: false,
    vote_average: 8.478,
    vote_count: 23160,
  },
  {
    adult: false,
    backdrop_path: "/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    popularity: 119.465,
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.477,
    vote_count: 26327,
  },
  {
    adult: false,
    backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
    genre_ids: [18, 80],
    id: 769,
    original_language: "en",
    original_title: "GoodFellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    popularity: 61.225,
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    title: "GoodFellas",
    video: false,
    vote_average: 8.467,
    vote_count: 12242,
  },
  {
    adult: false,
    backdrop_path: "/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg",
    genre_ids: [37],
    id: 429,
    original_language: "it",
    original_title: "Il buono, il brutto, il cattivo",
    overview:
      "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    popularity: 91.106,
    poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    release_date: "1966-12-22",
    title: "The Good, the Bad and the Ugly",
    video: false,
    vote_average: 8.467,
    vote_count: 8140,
  },
  {
    adult: false,
    backdrop_path: "/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg",
    genre_ids: [16, 18, 10752],
    id: 12477,
    original_language: "ja",
    original_title: "火垂るの墓",
    overview:
      "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
    popularity: 0.6,
    poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
    release_date: "1988-04-16",
    title: "Grave of the Fireflies",
    video: false,
    vote_average: 8.464,
    vote_count: 5158,
  },
  {
    adult: false,
    backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
    genre_ids: [18, 10749],
    id: 11216,
    original_language: "it",
    original_title: "Nuovo Cinema Paradiso",
    overview:
      "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    popularity: 38.065,
    poster_path: "/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg",
    release_date: "1988-11-17",
    title: "Cinema Paradiso",
    video: false,
    vote_average: 8.456,
    vote_count: 4148,
  },
  {
    adult: false,
    backdrop_path: "/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
    genre_ids: [28, 18],
    id: 346,
    original_language: "ja",
    original_title: "七人の侍",
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    popularity: 50.189,
    poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    release_date: "1954-04-26",
    title: "Seven Samurai",
    video: false,
    vote_average: 8.453,
    vote_count: 3433,
  },
  {
    adult: false,
    backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
    genre_ids: [35, 18],
    id: 637,
    original_language: "it",
    original_title: "La vita è bella",
    overview:
      "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    popularity: 46.86,
    poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    release_date: "1997-12-20",
    title: "Life Is Beautiful",
    video: false,
    vote_average: 8.453,
    vote_count: 12627,
  },
];

const upcomingMovies = [
  {
    adult: false,
    backdrop_path: "/gJL5kp5FMopB2sN4WZYnNT5uO0u.jpg",
    genre_ids: [28, 12, 16, 35, 10751],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 3781.812,
    poster_path: "/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 6.9,
    vote_count: 156,
  },
  {
    adult: false,
    backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: "en",
    original_title: "Land of Bad",
    overview:
      "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
    popularity: 1067.477,
    poster_path: "/lYwjlcBjokC9EhfzfAOkTMQd5Ku.jpg",
    release_date: "2024-01-25",
    title: "Land of Bad",
    video: false,
    vote_average: 6.994,
    vote_count: 348,
  },
  {
    adult: false,
    backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 806.344,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.114,
    vote_count: 7216,
  },
  {
    adult: false,
    backdrop_path: "/yKAg8z8T1iXeYA0Io3E4u9mchdt.jpg",
    genre_ids: [28, 878, 12],
    id: 823464,
    original_language: "en",
    original_title: "Godzilla x Kong: The New Empire",
    overview:
      "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    popularity: 543.985,
    poster_path: "/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
    release_date: "2024-03-27",
    title: "Godzilla x Kong: The New Empire",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
    genre_ids: [16, 12, 14],
    id: 508883,
    original_language: "ja",
    original_title: "君たちはどう生きるか",
    overview:
      "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
    popularity: 455.787,
    poster_path: "/f4oZTcfGrVTXKTWg157AwikXqmP.jpg",
    release_date: "2023-07-14",
    title: "The Boy and the Heron",
    video: false,
    vote_average: 7.4,
    vote_count: 1100,
  },
  {
    adult: false,
    backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
    genre_ids: [28, 53, 18],
    id: 866398,
    original_language: "en",
    original_title: "The Beekeeper",
    overview:
      "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    popularity: 466.179,
    poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
    release_date: "2024-01-08",
    title: "The Beekeeper",
    video: false,
    vote_average: 7.472,
    vote_count: 1732,
  },
  {
    adult: false,
    backdrop_path: "/xiAyufulheAWDWuZPVvV3Q9LIXc.jpg",
    genre_ids: [28],
    id: 799710,
    original_language: "ko",
    original_title: "더 와일드: 야수들의 전쟁",
    overview:
      "Woo-chul used to be a successful boxer, but he had to go to prison because his opponent died in the middle of a match. Now that he’s been released, he intends to become a model citizen. Meanwhile, his friend Do-shik will do whatever it takes to get ahead. After choosing different paths, they will be forced to plot against and betray one another.",
    popularity: 422.752,
    poster_path: "/otPBQncqsboG6MyAeGY8Pur7Vac.jpg",
    release_date: "2023-11-15",
    title: "The Wild",
    video: false,
    vote_average: 5.429,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/aINel9503ompOlGKn4sIVMg09Un.jpg",
    genre_ids: [9648, 27, 53],
    id: 838209,
    original_language: "ko",
    original_title: "파묘",
    overview:
      "After suffering from serial paranormal events, a wealthy family living in LA summons a young rising shaman duo Hwa-rim and Bong-gil to save the newborn of the family. Once they arrive, Hwa-rim senses a dark shadow of their ancestor has latched on the family, so-called a 'Grave's Calling'. In order to exhume the grave and relieve the ancestor, Hwa-rim seeks help from the top-notch geomancer Sang-duk and the mortician Young-geun. To their dismay, the four find the grave at a shady location in a remote village in Korea. Unaware of the consequences, the exhumation is carried out, yet this rather unleashes a malevolent force buried underneath.",
    popularity: 300.272,
    poster_path: "/pQYHouPsDw32FhDLr7E3jmw0WTk.jpg",
    release_date: "2024-02-22",
    title: "Exhuma",
    video: false,
    vote_average: 8.375,
    vote_count: 20,
  },
  {
    adult: false,
    backdrop_path: "/hIeEpk2w1dnC9ly9ZJwwbunH2Cx.jpg",
    genre_ids: [16, 35, 18, 10751],
    id: 838240,
    original_language: "xx",
    original_title: "Robot Dreams",
    overview:
      "Dog lives in Manhattan and he's tired of being alone. One day he decides to build himself a robot, a companion. Their friendship blossoms, until they become inseparable, to the rhythm of 80's NYC. One summer night, Dog, with great sadness, is forced to abandon Robot at the beach. Will they ever meet again?",
    popularity: 379.928,
    poster_path: "/vSzOobYVu16MogSALNg1bjTaGc.jpg",
    release_date: "2023-10-20",
    title: "Robot Dreams",
    video: false,
    vote_average: 7.5,
    vote_count: 115,
  },
  {
    adult: false,
    backdrop_path: "/bskmLsrwmpqvZxKDi81UHa4mFDx.jpg",
    genre_ids: [28, 18, 80],
    id: 944401,
    original_language: "en",
    original_title: "Dogman",
    overview:
      "A boy, bruised by life, finds his salvation through the love of his dogs.",
    popularity: 376.706,
    poster_path: "/yZGdlrKxglrWciRl0Rs6lAjfPHM.jpg",
    release_date: "2023-09-27",
    title: "Dogman",
    video: false,
    vote_average: 7.638,
    vote_count: 476,
  },
  {
    adult: false,
    backdrop_path: "/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
    genre_ids: [28, 35],
    id: 897087,
    original_language: "en",
    original_title: "Freelance",
    overview:
      "An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.",
    popularity: 261.847,
    poster_path: "/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg",
    release_date: "2023-10-05",
    title: "Freelance",
    video: false,
    vote_average: 6.526,
    vote_count: 625,
  },
  {
    adult: false,
    backdrop_path: "/aPQsU3yLDUOhLJYnSqkhKRkQTAw.jpg",
    genre_ids: [36, 18, 10752],
    id: 467244,
    original_language: "en",
    original_title: "The Zone of Interest",
    overview:
      "The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig, strive to build a dream life for their family in a house and garden next to the camp.",
    popularity: 206.477,
    poster_path: "/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg",
    release_date: "2023-12-15",
    title: "The Zone of Interest",
    video: false,
    vote_average: 7.3,
    vote_count: 844,
  },
  {
    adult: false,
    backdrop_path: "/fGe1ej335XbqN1j9teoDpofpbLX.jpg",
    genre_ids: [53, 9648, 80],
    id: 915935,
    original_language: "fr",
    original_title: "Anatomie d'une chute",
    overview:
      "A woman is suspected of her husband's murder, and their blind son faces a moral dilemma as the sole witness.",
    popularity: 192.084,
    poster_path: "/kQs6keheMwCxJxrzV83VUwFtHkB.jpg",
    release_date: "2023-08-23",
    title: "Anatomy of a Fall",
    video: false,
    vote_average: 7.658,
    vote_count: 1443,
  },
  {
    adult: false,
    backdrop_path: "/okXIAgFc2U6jf4uZrivhwEu7vbW.jpg",
    genre_ids: [35, 14],
    id: 823482,
    original_language: "en",
    original_title: "Dream Scenario",
    overview:
      "Hapless family man Paul Matthews finds his life turned upside down when millions of strangers suddenly start seeing him in their dreams. But when his nighttime appearances take a nightmarish turn, Paul is forced to navigate his newfound stardom.",
    popularity: 187.605,
    poster_path: "/zhEaG0KQ32KerHEWmImsYLexDix.jpg",
    release_date: "2023-11-10",
    title: "Dream Scenario",
    video: false,
    vote_average: 6.8,
    vote_count: 478,
  },
  {
    adult: false,
    backdrop_path: "/ae48U4187XzjJ7En7YTAIz2QKQC.jpg",
    genre_ids: [18],
    id: 976893,
    original_language: "ja",
    original_title: "PERFECT DAYS",
    overview:
      "Hirayama is content with his life as a toilet cleaner in Tokyo. Outside of his structured routine, he cherishes music on cassette tapes, books, and taking photos of trees. Through unexpected encounters, he reflects on finding beauty in the world.",
    popularity: 174.896,
    poster_path: "/mjEk5Wwx6TYVqw29zSaUHclMIgp.jpg",
    release_date: "2023-11-10",
    title: "Perfect Days",
    video: false,
    vote_average: 7.931,
    vote_count: 565,
  },
  {
    adult: false,
    backdrop_path: "/47SVqaO02doJ06tOmrjiWDkwU3T.jpg",
    genre_ids: [28, 53],
    id: 927107,
    original_language: "en",
    original_title: "The Bricklayer",
    overview:
      "Someone is blackmailing the CIA by assassinating foreign journalists and making it look like the agency is responsible. As the world begins to unite against the U.S., the CIA must lure its most brilliant – and rebellious – operative out of retirement, forcing him to confront his checkered past while unraveling an international conspiracy.",
    popularity: 148.291,
    poster_path: "/36pYugctLa70NmwMEgXTR1G31Kq.jpg",
    release_date: "2023-12-14",
    title: "The Bricklayer",
    video: false,
    vote_average: 6.033,
    vote_count: 136,
  },
  {
    adult: false,
    backdrop_path: "/p9DKeXp6FPJtAQ1k13Z4zPWrCbN.jpg",
    genre_ids: [18],
    id: 1058694,
    original_language: "en",
    original_title: "Radical",
    overview:
      "In a Mexican border town plagued by neglect, corruption, and violence, a frustrated teacher tries a radical new method to break through his students’ apathy and unlock their curiosity, their potential… and maybe even their genius.",
    popularity: 148.189,
    poster_path: "/eSatbygYZp8ooprBHZdb6GFZxGB.jpg",
    release_date: "2023-10-19",
    title: "Radical",
    video: false,
    vote_average: 8.417,
    vote_count: 326,
  },
  {
    adult: false,
    backdrop_path: "/7grv5ULlK9wMr2T1fkgr56HlbT.jpg",
    genre_ids: [18, 36, 10752],
    id: 760774,
    original_language: "en",
    original_title: "One Life",
    overview:
      "British stockbroker Nicholas Winton visits Czechoslovakia in the 1930s and forms plans to assist in the rescue of Jewish children before the onset of World War II, in an operation that came to be known as the Kindertransport.",
    popularity: 166.156,
    poster_path: "/yvnIWt2j8VnDgwKJE2VMiFMa2Qo.jpg",
    release_date: "2023-09-09",
    title: "One Life",
    video: false,
    vote_average: 7.729,
    vote_count: 210,
  },
  {
    adult: false,
    backdrop_path: "/zVMdsmRUH2U1bZSYr8GLZkfs3mi.jpg",
    genre_ids: [35, 80],
    id: 957304,
    original_language: "en",
    original_title: "Drive-Away Dolls",
    overview:
      "Jamie, an uninhibited free spirit bemoaning yet another breakup with a girlfriend, and her demure friend Marian desperately needs to loosen up. In search of a fresh start, the two embark on an impromptu road trip to Tallahassee, but things quickly go awry when they cross paths with a group of inept criminals along the way.",
    popularity: 101.995,
    poster_path: "/gavGnAMTXPkpoFgG0stwgIgKb64.jpg",
    release_date: "2024-02-22",
    title: "Drive-Away Dolls",
    video: false,
    vote_average: 5.9,
    vote_count: 83,
  },
  {
    adult: false,
    backdrop_path: "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
    genre_ids: [16, 35, 14, 12, 10751],
    id: 508943,
    original_language: "en",
    original_title: "Luca",
    overview:
      "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
    popularity: 119.193,
    poster_path: "/9x4i9uKGXt8IiiIF5Ey0DIoY738.jpg",
    release_date: "2021-06-17",
    title: "Luca",
    video: false,
    vote_average: 7.84,
    vote_count: 7969,
  },
];

const trailerVideo = {
  iso_639_1: "en",
  iso_3166_1: "US",
  name: "Official Trailer",
  key: "Sy6eNs3EW3E",
  site: "YouTube",
  size: 1080,
  type: "Trailer",
  official: true,
  published_at: "2023-09-28T07:00:49.000Z",
  id: "651528d2c50ad200ad7ef7dd",
};

export {
  nowPlayingMovies,
  popularMovies,
  topRatedMovies,
  upcomingMovies,
  trailerVideo,
};
